# List v/s NumPy Array
## 3 - main benefits of numpy array over python list
### 1) Less Memory
### 2) Fast 
### 3) Convinient

# #1 - Less Memory Comparison

In [1]:
import numpy as np

In [2]:
import sys

In [3]:
import time

In [4]:
list = range(1000)

## Python List

In [5]:
print(sys.getsizeof(5)*len(list))

28000


In [6]:
num_arr = np.arange(1000)

## NumPy Array

In [7]:
print(num_arr.size*num_arr.itemsize)

4000


# # 2 - Fast Comparison

In [8]:
#In Numpy array, 1 element takes 4 bytes where as in List, 1 object takes 14 bytes that's why NumPy array is fast as compared to List

In [9]:
SIZE = 1000000

In [10]:
l1 = range(SIZE)

In [11]:
l2 =  range(SIZE)

In [12]:
numarr1 = np.arange(SIZE)

In [13]:
numarr2 = np.arange(SIZE)

In [14]:
start = time.time()

## Python List

In [15]:
rslt_list = [(x+y) for x,y in zip(l1,l2)]

In [16]:
print("python list took",(time.time()-start)*1000)

python list took 95.46327590942383


## NumPy Array

In [17]:
start = time.time()

In [18]:
rslt_numarr = numarr1 + numarr2

In [19]:
print("Numpy took",(time.time()-start)*1000)

Numpy took 32.018184661865234


# # 3 - Convinient Comparison

## Python List

In [20]:
list = [1,2,3,4]

In [21]:
list2 = [5,6,7,8]

In [22]:
list + list2   # adding 2 list will merge 2 list instead of adding elements. To add 2 list we have to use List Comprehension

[1, 2, 3, 4, 5, 6, 7, 8]

## NumPy Array

In [23]:
n1 = np.array([1,2,3,4])

In [24]:
n2 = np.array([5,6,7,8])

In [25]:
n1 + n2       # adding or related operation can easily implemented on NumPy array instead of using comprehension

array([ 6,  8, 10, 12])

In [26]:
n1 - n2

array([-4, -4, -4, -4])

In [27]:
n1 * n2

array([ 5, 12, 21, 32])

In [28]:
n1 / n2

array([0.2       , 0.33333333, 0.42857143, 0.5       ])