**Numpy is a linear algebra library for Python, the reason it is so important for data science with python is that almost all the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.**



***Numpy is also incredibly fast, as it has bindings to C libraries.***

# 1) O-D array

In [1]:
import numpy as np

In [2]:
arr = np.array(42)

In [3]:
arr

array(42)

# 2) 1-D array

In [4]:
arr1 = np.array([1, 2, 3, 4, 5])

In [5]:
arr1

array([1, 2, 3, 4, 5])

# 3) 2-D array

In [6]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

In [7]:
arr2

array([[1, 2, 3],
       [4, 5, 6]])

# 4) 3-D array

In [8]:
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [9]:
arr3

array([[[1, 2, 3],
        [4, 5, 6]],

       [[1, 2, 3],
        [4, 5, 6]]])

## Check number of dimension

In [10]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

In [11]:
a.ndim

0

In [12]:
b.ndim

1

In [13]:
c.ndim

2

In [14]:
d.ndim

3

# Access array elements

### IN 1-D array

In [15]:
arr4 = np.array([1, 2, 3, 4])

In [16]:
arr4[0]

1

In [17]:
arr4[2]

3

In [18]:
arr4[1],arr4[3]   #getting element at index 1 & 3

(2, 4)

### IN 2-D array

In [19]:
arr5 = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [20]:
arr5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [21]:
arr5[0,1] #or 

2

In [22]:
arr5[1][2]   

8

In [23]:
arr5[0:2,2]

array([3, 8])

In [24]:
arr5[-1]

array([ 6,  7,  8,  9, 10])

### IN 3-D array

In [25]:
arr6 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [26]:
arr6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
arr6[0, 1]

2

In [28]:
arr6[2,1:2]

array([8])

In [29]:
arr6[-1,0:2]

array([7, 8])

In [30]:
arr6[:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

### Negative indexing

In [31]:
arr7 = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [32]:
arr7

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [33]:
arr7[1, -1]

10

# Slicing

### IN 1-D array

In [34]:
import numpy as np

In [35]:
arr8 = np.array([1, 2, 3, 4, 5, 6, 7])

In [36]:
arr8

array([1, 2, 3, 4, 5, 6, 7])

In [37]:
arr8[1:5]

array([2, 3, 4, 5])

In [38]:
arr8[4:]

array([5, 6, 7])

In [39]:
arr8[:4]

array([1, 2, 3, 4])

In [40]:
arr8[-1]

7

In [41]:
arr8[-3:-1]

array([5, 6])

### Using step

In [42]:
arr8[1:5:2]

array([2, 4])

In [43]:
arr8[::2]

array([1, 3, 5, 7])

### IN 2-D array

In [44]:
arr9 = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [45]:
arr9[0,1:5]

array([2, 3, 4, 5])

In [46]:
arr9[1,0:5:2]

array([ 6,  8, 10])

In [47]:
arr9[0:2, 1:4]

array([[2, 3, 4],
       [7, 8, 9]])

# Iterate through Array

In [48]:
arr10 = np.array([[6,7,8],[1,2,3],[4,5,6]])

In [49]:
arr10

array([[6, 7, 8],
       [1, 2, 3],
       [4, 5, 6]])

In [50]:
for row in arr10:
    print(row)

[6 7 8]
[1 2 3]
[4 5 6]


In [51]:
for cell in arr10.flat:
    print(cell)

6
7
8
1
2
3
4
5
6


# Stacking

In [52]:
a = np.arange(6).reshape(3,2)

In [53]:
b = np.arange(6,12).reshape(3,2)

In [54]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [55]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [56]:
np.vstack((a,b))               #vertical stacking

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [57]:
np.hstack((a,b))             # horizontal stacking

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

# Spliting

In [58]:
c = np.arange(30).reshape(2,15)

In [59]:
c

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [60]:
rslt = np.hsplit(c,3)                # horizantally split into 3 different arrays

In [61]:
rslt

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [62]:
rslt[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [63]:
rslt[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [64]:
rslt[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [65]:
rslt = np.vsplit(c,2)

In [66]:
rslt

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]]),
 array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])]

In [67]:
rslt[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [68]:
rslt[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

# Indexing With Boolean

In [69]:
a = np.arange(12).reshape(3,4)

In [70]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [71]:
b = d > 4              # will return true where element in b is greater than 4 else return false

In [72]:
b

array([[[False, False, False],
        [False,  True,  True]],

       [[False, False, False],
        [False,  True,  True]]])