In [1]:
import numpy as np

In [2]:
a = np.array([5,6,9])                            #1-dimesnional array

In [3]:
a2 = np.array([[1,2,3],[4,5,6],[7,8,9]])         # 2-dimensional array

In [4]:
a[0]

5

In [5]:
a2[2,0]

7

# Properties

## ndim

In [6]:
a.ndim

1

In [7]:
a2.ndim

2

## itemsize 

In [8]:
a.itemsize

4

In [9]:
a2.itemsize

4

## dtype 

In [10]:
a.dtype

dtype('int32')

In [11]:
a2.dtype

dtype('int32')

## change datatype of element

In [12]:
a3 = np.array([11,22,33], dtype=np.float64)          #changing data type 

In [13]:
a3.dtype

dtype('float64')

## size 

In [14]:
a

array([5, 6, 9])

In [15]:
a.size

3

In [16]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
a2.size

9

## shape 

In [18]:
a.shape

(3,)

In [19]:
a2.shape

(3, 3)

In [20]:
a3 = np.array([[1,2],[3,4],[5,6]], dtype=complex)

In [21]:
a3

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [22]:
a3.dtype

dtype('complex128')

## Zeros() 

In [23]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Ones()

In [24]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## arange()

In [25]:
np.arange(1,5)

array([1, 2, 3, 4])

In [26]:
np.arange(1,5,2)       # with step

array([1, 3])

## linspace()

In [27]:
np.linspace(1,5,10)    # to generate linearly spaced 10 number from 1 to 5

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

## reshape()

In [28]:
a3 = np.array([[1,2],[3,4],[5,6]])

In [29]:
a3.shape

(3, 2)

In [30]:
a3.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
a3.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [32]:
a3.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [33]:
a2.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

## ravel()

In [34]:
a2.ravel()            # to flat N-Dimensional Array to flat array or 1-D Array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
a3.ravel()

array([1, 2, 3, 4, 5, 6])

In [36]:
a3    # ravel property don't touch/alter the original array to store the 1D array we have captured in new variable as below

array([[1, 2],
       [3, 4],
       [5, 6]])

In [37]:
a4 = a3.ravel()

In [38]:
a4

array([1, 2, 3, 4, 5, 6])

## min() & max()

In [39]:
a2.min()

1

In [40]:
a2.max()

9

## sum()

In [41]:
a2.sum()

45

### axis

In [42]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
a2.sum(axis=0)

array([12, 15, 18])

In [44]:
a2.sum(axis=1)

array([ 6, 15, 24])

## sqrt()

In [45]:
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
np.sqrt(a2)      

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

## std()

In [48]:
np.std(a2)                        # standard deviation of a2

2.581988897471611

## basic maths operation

In [49]:
a_1 = np.array([[1,2],[3,4]])

In [50]:
a_2 = np.array([[5,6],[7,8]])

In [52]:
a_1

array([[1, 2],
       [3, 4]])

In [53]:
a_2

array([[5, 6],
       [7, 8]])

In [54]:
a_1 + a_2

array([[ 6,  8],
       [10, 12]])

In [55]:
a_1 - a_2

array([[-4, -4],
       [-4, -4]])

In [56]:
a_1 * a_2

array([[ 5, 12],
       [21, 32]])

In [57]:
a_1 / a_2

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

## matrix dot product

In [58]:
a_1.dot(a_2)

array([[19, 22],
       [43, 50]])